version: '3'
services:
  api:
    build:
      context: ./api
      args:
        app_env: ${APP_ENV}
    volumes:
      - ./api:/go/src/github.com/czapla/progressify-server/api
    ports:
      - "10000:10000"

  redis:
    image: "redis:alpine"